### ISSUE TITLE
make max_entries configurable

### ISSUE THREAD

**Issue by NotAShelf** [n3oney/anyrun-nixos-options#2]
to fit anyrun in my screen (and avoid crashes) I must set the max entries value to something like 5, which displays way too few results for other plugins

might be a good idea to have max entries configurable specific to this plugin, similar to how the symbols plugin does it.

**Comment by n3oney** [comment]
implemented in https://github.com/n3oney/anyrun-nixos-options/commit/aed824957538e65dc3bea414aadbe5e2de611f49
